version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      test-tooling:
        patterns:
          - "org.junit*"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - dependencies
